version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    restart: always
    ports:
      - "1884:1883"   # MQTT
      - "8884:8883"   # MQTT over SSL
      - "9004:9001"   # WebSocket
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/passwd:/mosquitto/config/passwd
      - ./config/acls:/mosquitto/config/acls
      - ./config/certs:/mosquitto/certs
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      - ./scripts/add-users.sh:/usr/local/bin/add-users.sh
      - ./config/users.txt:/mosquitto/config/users.txt
    entrypoint: ["/bin/sh", "-c", "/usr/local/bin/add-users.sh && mosquitto -c /mosquitto/config/mosquitto.conf"]
    environment:
      - TZ=Asia/Kolkata

  redis:
    image: redis:7
    container_name: redis-cache
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
